COPENS/COPENS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from copens_static_pages import views
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('user/', include('createcorpora.urls', namespace='create')),
    path('', include('copens_static_pages.urls', namespace='static_pages')),
    path('django-rq/', include('django_rq.urls'))
]

urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls))
    ]

COPENS/copens_static_pages/urls.py
from django.urls import path
from . import views

app_name = 'copens_static_pages'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('about', views.About.as_view(), name='about'),
    path('term_of_use', views.TermOfUse.as_view(), name='term_of_use'),
    path('contact', views.Contact.as_view(), name='contact'),
    path('api_doc', views.ApiDoc.as_view(), name='api_doc'),
    path('query', views.Query.as_view(), name='query'),
    path('result', views.ConcordanceResultView.as_view(), name='concordance_result'),
    path('concordance', views.ConcordanceQueryView.as_view(), name='concordance'),
    path('wordlist_result', views.WordlistResultView.as_view(), name='wordlist_result'),
    path('wordlist', views.WordListQueryView.as_view(), name='wordlist'),
    path('word_sketch', views.WordSketchQueryView.as_view(), name='word_sketch'),
    path('word_sketch_result', views.WordSketchResultView.as_view(), name='word_sketch_result'),
    path('collocation', views.CollocationQueryView.as_view(), name='collocation'),
    path('collocation_result', views.CollocationResultView.as_view(), name='collocation_result'),
    path('output_csv', views.output_csv, name='output_csv'),






    # path('create/', UploadCorporaView.as_view(), name='upload')
]

COPENS/copens_static_pages/models.py
from django.db import models

# Create your models here.

COPENS/copens_static_pages/views.py
import csv
import logging

from django.contrib import messages
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import TemplateView, View
from django.views.generic.edit import FormView
from django.http import StreamingHttpResponse

from django.db.models import Q
from django.contrib.auth.models import AnonymousUser

from createcorpora.models import Corpus, CopensUser


from .forms import ConcordanceForm, WordlistForm, WordSketchForm, CollocationForm

from createcorpora import utils
from createcorpora.views import for_concordance_tag

logger = logging.getLogger(__name__)

# Create your views here.
class Home(TemplateView):
    template_name = 'copens_static_pages/home.html'

    def get_context_data(self, *args, **kwargs):
        context = super(Home, self).get_context_data(*args, **kwargs)
        context['home'] = True
        return context

class About(TemplateView):
    template_name = 'copens_static_pages/about.html'


class TermOfUse(TemplateView):
    template_name = 'copens_static_pages/term_of_use.html'


class Contact(TemplateView):
    template_name = 'copens_static_pages/contact.html'


class ApiDoc(TemplateView):
    template_name = 'copens_static_pages/api_doc.html'


class Query(TemplateView):
    template_name = 'copens_static_pages/query.html'



class ConcordanceQueryView(FormView):
    """
    搜尋Concordance的頁面
    """

    template_name = 'copens_static_pages/query_concordance.html'
    form_class = ConcordanceForm

    def get_form_kwargs(self):
        """
        Add the current logged in user to the form's context.
        """
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_invalid(self, form):
        print(form.errors)


class ConcordanceResultView(View):
    """
    顯示搜尋Concordance的結果頁面。
    """
    template_name = 'copens_static_pages/result_concordance.html'

    def get(self, request):
        if not self.request.GET.getlist('corpora'):
            messages.warning(self.request, '請至少選擇一個語料庫')
            return redirect('static_pages:concordance')

        if self.request.GET.get('page'):
            results_list = self.request.session.get('results_list')
            paginator = Paginator(results_list, 20)
            page = request.GET.get('page')
            results = paginator.get_page(page)
            results.total = len(results_list)
            results.object_list = list(map(for_concordance_tag, results.object_list))
            return render(request, self.template_name, {'results': results})

        form = ConcordanceForm(self.request.GET, user=self.request.user)

        if form.is_valid():
            results_list = []
            if self.request.user.is_authenticated:
                user_registry = utils.get_user_registry(self.request)
                print(user_registry)
            else:
                user_registry = None
            results_dict = utils.cqp_query(user_registry=user_registry, **form.cleaned_data)
            self.request.session['results_dict'] = results_dict
            print(results_dict)
            for corpus, path in results_dict.items():
                print(corpus, path)
                try:
                    results_list.extend(utils.read_results(path))
                except FileNotFoundError:
                    messages.error(request, '查詢語法有誤！')
                    return redirect('static_pages:concordance')

            paginator = Paginator(results_list, 50)
            page = request.GET.get('page')
            results = paginator.get_page(page)
            results.total = len(results_list)
            results.object_list = list(map(for_concordance_tag, results.object_list))
            self.request.session['results_list'] = results_list
            print(results.object_list)
            return render(request, self.template_name, {'results': results})
        else:
            print(form.errors)
            return redirect('static_pages:concordance')

class WordListQueryView(FormView):
    """
    User chooses what databases to query from.
    """

    template_name = 'copens_static_pages/query_wordlist.html'
    form_class = WordlistForm

    def get_form_kwargs(self):
        """
        Add the current logged in user to the form's context.
        """
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_invalid(self, form):
        print(form.errors)

class WordlistResultView(View):
    """
    顯示搜尋Word list的結果頁面。
    """
    template_name = 'copens_static_pages/result_wordlist.html'

    def get(self, request):
        if not self.request.GET.getlist('corpus'):
            messages.warning(self.request, '請至少選擇一個語料庫')
            return redirect('static_pages:wordlist')

        # if self.request.GET.get('page'):
        #     results_list = self.request.session.get('results_list')
        #     paginator = Paginator(results_list, 20)
        #     page = request.GET.get('page')
        #     results = paginator.get_page(page)
        #     results.total = len(results_list)
        #     results.object_list = list(map(for_concordance_tag, results.object_list))
        #     return render(request, self.template_name, {'results': results})

        form = WordlistForm(self.request.GET, user=self.request.user)
        # print(form.is_valid())
        if form.is_valid():
            results_list = []
            if self.request.user.is_authenticated:
                user_registry = utils.get_user_registry(self.request)
                print(user_registry)
            else:
                user_registry = None
            list_of_words = utils.cqp_query_wordlist(user_registry=user_registry, **form.cleaned_data)
            # print(type(list_of_words))
            # print(list_of_words)
            results = (word.strip().split('\t') for word in list_of_words)
            # print(results)
            # self.request.session['results_dict'] = results_dict
            # print(results_dict)
            # for corpus, path in results_dict.items():
            #     print(corpus, path)
            #     try:
            #         results_list.extend(utils.read_results(path))
            #     except FileNotFoundError:
            #         messages.error(request, '查詢語法有誤！')
            #         return redirect('static_pages:concordance')

            # paginator = Paginator(results_list, 50)
            # page = request.GET.get('page')
            # results = paginator.get_page(page)
            # results.total = len(results_list)
            # results.object_list = list(map(for_concordance_tag, results.object_list))
            # self.request.session['results_list'] = results_list
            # print(results.object_list)
            return render(request, self.template_name, {'results': results})
        else:
            print(form.errors)
            return redirect('static_pages:wordlist')


    # def get_context_data(self, *args, **kwargs):
    #     context = super(Home, self).get_context_data(*args, **kwargs)
    #     # Generate DB_CHOICES based on AnonymousUser / Logined User

    #     if self.request.user.is_authenticated:
    #         DB_CHOICES = [(c.file_name.split('.')[0], f'{c.zh_name} / {c.owner}')  # value, label
    #                        for c in Corpus.objects.filter(Q(owner=self.copens_user) | Q(is_public=True))]
    #     else:
    #         DB_CHOICES = [(c.file_name.split('.')[0], f'{c.zh_name}')  # value, label
    #                        for c in Corpus.objects.filter(Q(is_public=True))]
            
        
    #     super().__init__(*args, **kwargs)  # must call super() to have access to fields
    #     return context

    # def get_form_kwargs(self):
    #     """
    #     Add the current logged in user to the form's context.
    #     """
    #     kwargs = super().get_form_kwargs()

    #     kwargs['user'] = self.request.user
    #     return kwargs

    # def form_invalid(self, form):
    #     print(form.errors)

class Echo:
    """An object that implements just the write method of the file-like
    interface.
    """
    def write(self, value):
        """Write the value by returning it, instead of storing in a buffer."""
        return value

def output_csv(request):
    """A view that streams a large CSV file."""
    # Generate a sequence of rows. The range is based on the maximum number of
    # rows that can be handled by a single sheet in most spreadsheet
    # applications.
    rows = []
    for (corpus_name, file_path) in request.session['results_dict'].items():
        with open(file_path) as f:
            for line in f:
                if '<HR>' in line or 'UL>' in line:
                    continue
                else:
                    line_dict = for_concordance_tag(line)
                    rows.append([corpus_name, line_dict['context_left'], line_dict['query_word'], line_dict['context_right']])
    # rows = (["Row {}".format(idx), str(idx)] for idx in range(65536))
    pseudo_buffer = Echo()
    writer = csv.writer(pseudo_buffer)
    response = StreamingHttpResponse((writer.writerow(row) for row in rows),
                                     content_type="text/csv")
    response['Content-Disposition'] = 'attachment; filename="copens_concordance_output.csv"'
    return response


# 2019-08-09: Word sketch
class WordSketchQueryView(FormView):
    """
    User chooses what databases to query from.
    """

    template_name = 'copens_static_pages/query_word_sketch.html'
    form_class = WordSketchForm

    def get_form_kwargs(self):
        """
        Add the current logged in user to the form's context.
        """
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_invalid(self, form):
        print(form.errors)

class WordSketchResultView(View):
    """
    顯示搜尋Word list的結果頁面。
    """

COPENS/templates/copens_static_pages/generic/base.html
{% load static %}
{% load account socialaccount %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-116959239-2"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }

        gtag('js', new Date());

        gtag('config', 'UA-116959239-2');
    </script>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>COPENS</title>
    <meta name="description" content="COPENS">
    <meta name="keywords" content="COPENS, corpus">
    <meta name="author" content="LOPE">

    <!-- Favicon -->
    <link rel="icon" type="image/png" href="http://demo.tempload.com/babil/assets/images/favicon/favicon.png">

    <!-- Bootstrap 4.1.3 CSS -->
    <!--
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet"
          type="text/css">
        -->

    <!-- FontAwesome CSS -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css"
          integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

    <!--

    <link rel="stylesheet" type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/10.4.0/css/bootstrap-slider.min.css">
    -->

    <!-- Materialize 1.0.0 CSS: Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- Material icons -->

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/copens.css' %}" rel="stylesheet" type="text/css">


</head>
<body>

{% include "./modal/login_modal.html" %}

{% include "./navbar.html" %}

{% if not home %}
<div class="row" id="page_header">
    <div class="container">
        <div class="col s12 section" style="padding: 15px 0">
            {% block page_header %}
            {% endblock page_header %}
        </div>
    </div>
</div>
{% endif %}

{% block content %}
{% endblock content %}

{% include "./footer.html" %}


<!-- jQuery -->
<!--
<script
  src="http://code.jquery.com/jquery-2.2.4.min.js"
  integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
  crossorigin="anonymous"></script>
-->

<!--

<script src="https://unpkg.com/bootstrap-material-design@4.1.1/dist/js/bootstrap-material-design.js"
        integrity="sha384-CauSuKpEqAFajSpkdjv3z9t8E7RlpJ1UP0lKM/+NdtSarroVKu069AlsRPKkFBz9"
        crossorigin="anonymous"></script>
<script>
    $('body').bootstrapMaterialDesign();
</script>

-->

<!-- Plugins -->
<script>
    /*! Scroll Reveal Animations */
    window.scrollReveal = function (t) {
        "use strict";

        function e(e) {
            this.docElem = t.document.documentElement, this.options = this.extend(this.defaults, e), this.styleBank = {}, 1 == this.options.init && this.init()
        }

        var i = 1, o = function () {
            return t.requestAnimationFrame || t.webkitRequestAnimationFrame || t.mozRequestAnimationFrame || function (e) {
                t.setTimeout(e, 1e3 / 60)
            }
        }();
        return e.prototype = {
            defaults: {
                after: "0s",
                enter: "bottom",
                move: "24px",
                over: "0.66s",
                easing: "ease-in-out",
                opacity: 0,
                viewportFactor: .33,
                reset: !1,
                init: !0
            }, init: function () {
                this.scrolled = !1;
                var e = this;
                this.elems = Array.prototype.slice.call(this.docElem.querySelectorAll("[data-scroll-reveal]")), this.elems.forEach(function (t, o) {
                    var r = t.getAttribute("data-scroll-reveal-id");
                    r || (r = i++, t.setAttribute("data-scroll-reveal-id", r)), e.styleBank[r] || (e.styleBank[r] = t.getAttribute("style")), e.update(t)
                });
                var r = function (t) {
                    e.scrolled || (e.scrolled = !0, o(function () {
                        e._scrollPage()
                    }))
                }, n = function () {
                    function t() {
                        e._scrollPage(), e.resizeTimeout = null
                    }

                    e.resizeTimeout && clearTimeout(e.resizeTimeout), e.resizeTimeout = setTimeout(t, 200)
                };
                t.addEventListener("scroll", r, !1), t.addEventListener("resize", n, !1)
            }, _scrollPage: function () {
                var t = this;
                this.elems.forEach(function (e, i) {
                    t.update(e)
                }), this.scrolled = !1
            }, parseLanguage: function (t) {
                function e(t) {
                    var e = [], i = ["from", "the", "and", "then", "but", "with"];
                    return t.forEach(function (t, o) {
                        i.indexOf(t) > -1 || e.push(t)
                    }), e
                }

                var i = t.getAttribute("data-scroll-reveal").split(/[, ]+/), o = {};
                return i = e(i), i.forEach(function (t, e) {
                    switch (t) {
                        case"enter":
                            return void (o.enter = i[e + 1]);
                        case"after":
                            return void (o.after = i[e + 1]);
                        case"wait":
                            return void (o.after = i[e + 1]);
                        case"move":
                            return void (o.move = i[e + 1]);
                        case"ease":
                            return o.move = i[e + 1], void (o.ease = "ease");
                        case"ease-in":
                            return o.move = i[e + 1], void (o.easing = "ease-in");
                        case"ease-in-out":
                            return o.move = i[e + 1], void (o.easing = "ease-in-out");
                        case"ease-out":
                            return o.move = i[e + 1], void (o.easing = "ease-out");
                        case"over":
                            return void (o.over = i[e + 1]);
                        default:
                            return
                    }
                }), o
            }, update: function (t) {
                var e = this.genCSS(t), i = this.styleBank[t.getAttribute("data-scroll-reveal-id")];
                return null != i ? i += ";" : i = "", t.getAttribute("data-scroll-reveal-initialized") || (t.setAttribute("style", i + e.initial), t.setAttribute("data-scroll-reveal-initialized", !0)), this.isElementInViewport(t, this.options.viewportFactor) ? t.getAttribute("data-scroll-reveal-complete") ? void 0 : this.isElementInViewport(t, this.options.viewportFactor) ? (t.setAttribute("style", i + e.target + e.transition), void (this.options.reset || setTimeout(function () {
                    "" != i ? t.setAttribute("style", i) : t.removeAttribute("style"), t.setAttribute("data-scroll-reveal-complete", !0)
                }, e.totalDuration))) : void 0 : void (this.options.reset && t.setAttribute("style", i + e.initial + e.reset))
            }, genCSS: function (t) {
                var e, i, o = this.parseLanguage(t);
                o.enter ? (("top" == o.enter || "bottom" == o.enter) && (e = o.enter, i = "y"), ("left" == o.enter || "right" == o.enter) && (e = o.enter, i = "x")) : (("top" == this.options.enter || "bottom" == this.options.enter) && (e = this.options.enter, i = "y"), ("left" == this.options.enter || "right" == this.options.enter) && (e = this.options.enter, i = "x")), ("top" == e || "left" == e) && (o.move ? o.move = "-" + o.move : o.move = "-" + this.options.move);
                var r = o.move || this.options.move, n = o.over || this.options.over, s = o.after || this.options.after,
                    a = o.easing || this.options.easing, l = o.opacity || this.options.opacity,
                    u = "-webkit-transition: -webkit-transform " + n + " " + a + " " + s + ",  opacity " + n + " " + a + " " + s + ";transition: transform " + n + " " + a + " " + s + ", opacity " + n + " " + a + " " + s + ";-webkit-perspective: 1000;-webkit-backface-visibility: hidden;",
                    c = "-webkit-transition: -webkit-transform " + n + " " + a + " 0s,  opacity " + n + " " + a + " " + s + ";transition: transform " + n + " " + a + " 0s,  opacity " + n + " " + a + " " + s + ";-webkit-perspective: 1000;-webkit-backface-visibility: hidden;",
                    f = "-webkit-transform: translate" + i + "(" + r + ");transform: translate" + i + "(" + r + ");opacity: " + l + ";",
                    p = "-webkit-transform: translate" + i + "(0);transform: translate" + i + "(0);opacity: 1;";
                return {
                    transition: u,
                    initial: f,
                    target: p,
                    reset: c,
                    totalDuration: 1e3 * (parseFloat(n) + parseFloat(s))
                }
            }, getViewportH: function () {
                var e = this.docElem.clientHeight, i = t.innerHeight;
                return i > e ? i : e
            }, getOffset: function (t) {
                var e = 0, i = 0;
                do isNaN(t.offsetTop) || (e += t.offsetTop), isNaN(t.offsetLeft) || (i += t.offsetLeft); while (t = t.offsetParent);
                return {top: e, left: i}
            }, isElementInViewport: function (e, i) {
                var o = t.pageYOffset, r = o + this.getViewportH(), n = e.offsetHeight, s = this.getOffset(e).top,
                    a = s + n, i = i || 0;
                return r >= s + n * i && a >= o || "fixed" == (e.currentStyle ? e.currentStyle : t.getComputedStyle(e, null)).position
            }, extend: function (t, e) {
                for (var i in e) e.hasOwnProperty(i) && (t[i] = e[i]);
                return t
            }
        }, e
    }(window);

</script>

<!--
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/10.4.0/bootstrap-slider.min.js"></script> -->
<!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
<!-- Global Init -->
<!--
<script src="{% static 'js/copens.js' %}">
</script>-->
<script>
    M.AutoInit();
</script>

{% block extra_js %}

{% endblock extra_js %}

</body>
</html>

COPENS/templates/copens_static_pages/generic/navbar.html
{% load static %}
<!--
<header class="header-area {% if not home %} not-index-header {% endif %} z-depth-5">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <nav class="main-nav">

                    <a href="{% url 'copens_static_pages:home' %}" class="logo">
              <img src="{% static 'images/copens_logo.svg' %}" class="light-logo" alt="COPENS" style="display: block;">

              {% if not home %}
              <img src="{% static 'images/copens_logo.svg' %}" class="dark-logo" alt="COPENS" style="display: none;">
              {% else %}
               <img src="{% static 'images/copens_logo_black.svg' %}" class="dark-logo" alt="COPENS" style="display: none;">
              {% endif %}
             
            </a>

                    <ul class="nav">
                        <li><a href="{% url 'copens_static_pages:home' %}">首頁</a></li>
                        <li>
                            <a href="{% url 'copens_static_pages:query' %}">語料庫</a>
                        </li>

                        <li class="submenu">
                            <a href="#">關於 <i class="fa fa-angle-down"></i></a>
                            <ul>
                                <li><a href="{% url 'copens_static_pages:about' %}">關於COPENS</a></li>
                                <li><a href="{% url 'copens_static_pages:term_of_use' %}">使用條款</a></li>
                                <li><a href="{% url 'copens_static_pages:contact' %}">聯絡我們</a></li>
                            </ul>
                        </li>
                        {% if user.is_authenticated %}
                            <li id="user_submenu" class="submenu">
                                <a class="btn-nav" href="#">歡迎 {{ user.get_username }} <i class="fa fa-angle-down"></i></a>
                                <ul>
                                    <li><a href="{% url 'create:home' %}">使用者後台</a></li>
                                    <li><form class="" method="POST" action="{% url 'account_logout' %}"><a href="#" onclick="$(this).closest('form').submit()">登出</a> {% csrf_token %}</form></li>
                                </ul>
                            </li>
                            
                                
                        {% else %}
                            <li><a class="btn-nav" data-toggle="modal" data-target="#loginModal">登入 | 註冊</a></li>
                        {% endif %}
                        
                    </ul>
                    <a class="menu-trigger" style="color: white">
              <span>Menu</span>
            </a>

                </nav>
            </div>
        </div>
    </div>
</header>
-->
<div class="{% if home %}navbar-fixed{% endif %}">

<!-- Dropdown: 關於 -->
<ul id="dropdown_about" class="dropdown-content">
    <li><a href="{% url 'copens_static_pages:about' %}">關於COPENS</a></li>
    <li><a href="{% url 'copens_static_pages:term_of_use' %}">使用條款</a></li>
    <li><a href="{% url 'copens_static_pages:contact' %}">聯絡我們</a></li>
</ul>

<!-- Dropdown: 使用者後台 -->
{% if user.is_authenticated %}
<ul id="dropdown_user" class="dropdown-content">
    <li><a href="{% url 'create:home' %}">使用者後台</a></li>
    <li><form class="" method="POST" action="{% url 'account_logout' %}"><a href="#" onclick="$(this).closest('form').submit()">登出</a> {% csrf_token %}</form></li>
</ul>
{% endif %}

<nav class="black-text z-depth-2">
    <div class="nav-wrapper container">
      <a href="{% url 'copens_static_pages:home' %}" class="brand-logo" id="lopen-logo">
          <img src="{% static 'images/copens_logo_black.svg' %}" class="dark-logo" alt="COPENS" style="display: block;">
          {% if not home %}
          <img src="{% static 'images/copens_logo_black.svg' %}" class="dark-logo" alt="COPENS" style="display: none;">
          {% else %}
           <img src="{% static 'images/copens_logo_black.svg' %}" class="dark-logo" alt="COPENS" style="display: none;">
          {% endif %}
      </a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a href="{% url 'copens_static_pages:home' %}">首頁</a></li>
        <li>
            <a href="{% url 'copens_static_pages:concordance' %}">語料庫</a>
        </li>

        <!-- 關於 Dropdown -->
        <li>
            <a class="dropdown-trigger" href="#!" data-target="dropdown_about">關於<i class="material-icons right">arrow_drop_down</i></a>
        </li>

        {% if user.is_authenticated %}
            <li>
                <a class="dropdown-trigger" href="#!" data-target="dropdown_user">歡迎 {{ user.get_username }} <i class="material-icons right">arrow_drop_down</i></a>
            </li>    
        {% else %}
            <li><a class="btn-nav" href="/accounts/login">登入 | 註冊</a></li>
          <!--
            <li><a class="btn-nav modal-trigger" href="#login-modal">登入 | 註冊</a></li>
          -->
            <!-- <li><a class="btn-nav" data-toggle="modal" data-target="#loginModal">登入 | 註冊</a></li> -->
        {% endif %}
      </ul>
    </div>
  </nav>
</div>

COPENS/templates/copens_static_pages/generic/page_header.html
<div class="row container">
      <div class="col s12 section">
            {% block page_header %}
            {% endblock page_header %}
      </div>
</div>

COPENS/templates/copens_static_pages/generic/query_nav.html
<div class="row">
    <div class="col s12">
        <ul class="tabs">
            <li class="tab col s3"><a target="_self" class="{% if current == 'concordance' %}active{% endif %}" href="{% url 'static_pages:concordance' %}">Concordance</a></li>
            <li class="tab col s3"><a target="_self" class="{% if current == 'wordlist' %}active{% endif %}" href="{% url 'static_pages:wordlist' %}">Word list</a></li>
            <li class="tab col s3"><a target="_self" class="{% if current == 'collocation' %}active{% endif %}" href="{% url 'static_pages:collocation' %}">Collocation</a></li>
            <li class="tab col s3"><a target="_self" class="{% if current == 'word_sketch' %}active{% endif %}" href="{% url 'static_pages:word_sketch' %}">Word Sketch</a></li>
        </ul>
    </div>
</div>