COPENS/COPENS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from copens_static_pages import views
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('user/', include('createcorpora.urls', namespace='create')),
    path('', include('copens_static_pages.urls', namespace='static_pages')),
    path('django-rq/', include('django_rq.urls'))
]

urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls))
    ]

COPENS/copens_static_pages/urls.py
from django.urls import path
from . import views

app_name = 'copens_static_pages'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('about', views.About.as_view(), name='about'),
    path('term_of_use', views.TermOfUse.as_view(), name='term_of_use'),
    path('contact', views.Contact.as_view(), name='contact'),
    path('api_doc', views.ApiDoc.as_view(), name='api_doc'),
    path('query', views.Query.as_view(), name='query'),
    path('result', views.ConcordanceResultView.as_view(), name='concordance_result'),
    path('concordance', views.ConcordanceQueryView.as_view(), name='concordance'),
    path('wordlist_result', views.WordlistResultView.as_view(), name='wordlist_result'),
    path('wordlist', views.WordListQueryView.as_view(), name='wordlist'),
    path('word_sketch', views.WordSketchQueryView.as_view(), name='word_sketch'),
    path('word_sketch_result', views.WordSketchResultView.as_view(), name='word_sketch_result'),
    path('collocation', views.CollocationQueryView.as_view(), name='collocation'),
    path('collocation_result', views.CollocationResultView.as_view(), name='collocation_result'),
    path('output_csv', views.output_csv, name='output_csv'),






    # path('create/', UploadCorporaView.as_view(), name='upload')
]

COPENS/copens_static_pages/models.py
from django.db import models

# Create your models here.

COPENS/copens_static_pages/forms.py
import logging

from crispy_forms.helper import FormHelper
from django import forms
from django.db.models import Q
from django.contrib.auth.models import AnonymousUser

from createcorpora.models import Corpus, CopensUser



logger = logging.getLogger(__name__)


class ConcordanceForm(forms.Form):
    """
    Form to search databases. Choices are populated with public corpora and a user's corpora, if logged in.
    """

    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.user = kwargs.pop('user', AnonymousUser())
        logging.debug('Authenticated!')

        # Generate DB_CHOICES based on AnonymousUser / Logined User
        if isinstance(self.user, AnonymousUser):
            self.DB_CHOICES = [(c.file_name.split('.')[0], f'{c.zh_name}')  # value, label
                           for c in Corpus.objects.filter(Q(is_public=True))]
        else:
            self.copens_user = CopensUser.objects.get(user=self.user)
            self.DB_CHOICES = [(c.file_name.split('.')[0], f'{c.zh_name} / {c.owner}')  # value, label
                           for c in Corpus.objects.filter(Q(owner=self.copens_user) | Q(is_public=True))]
        
        super().__init__(*args, **kwargs)  # must call super() to have access to fields

        # 要搜索的語料庫field
        try:
            self.fields['corpora'] = forms.MultipleChoiceField(
                label="選擇語料庫",
                choices=self.DB_CHOICES,
                widget=forms.CheckboxSelectMultiple,
                initial=self.DB_CHOICES[0]
            )

        except IndexError:
            self.fields['corpora'] = forms.MultipleChoiceField()

    # 要搜索的關鍵字field
    query = forms.CharField(
        max_length=255,
        initial='台北',
        help_text="""
            若要使用CQL，請您直接輸入CQL格式的索引，例 [pos = "V.*"][pos = "N.*"]
        """
    )

    # CHOICES = [(n, n) for n in range(1, 31)]
    # c = forms.ChoiceField(label="Window size", choices=[('a','v')])
    
    # 上下文視窗大小field
    context = forms.IntegerField(
        label='視窗大小',
        widget=forms.NumberInput(attrs={'type': 'range', 'min': 5, 'max': 30}),
        initial=10,
    ) 

    # 是否顯示詞性field
    show_pos = forms.BooleanField(
        label="顯示詞性(POS)",
        required=False
    )


class WordlistForm(forms.Form):
    """
    Form to answer which corpus to generate wordlist.
    """

    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.user = kwargs.pop('user', AnonymousUser())
        logging.debug('Authenticated!')

        # Generate DB_CHOICES based on AnonymousUser / Logined User
        if isinstance(self.user, AnonymousUser):
            self.DB_CHOICES = [(c.file_name.split('.')[0], f'{c.zh_name}')  # value, label
                           for c in Corpus.objects.filter(Q(is_public=True))]
        else:
            self.copens_user = CopensUser.objects.get(user=self.user)
            self.DB_CHOICES = [(c.file_name.split('.')[0], f'{c.zh_name} / {c.owner}')  # value, label
                           for c in Corpus.objects.filter(Q(owner=self.copens_user) | Q(is_public=True))]
        
        super().__init__(*args, **kwargs)  # must call super() to have access to fields

        # 要搜索的語料庫field
        try:
            self.fields['corpus'] = forms.ChoiceField(
                label="選擇語料庫",
                choices=self.DB_CHOICES,
                # widget=forms.CheckboxSelectMultiple,
                widget=forms.RadioSelect,
                initial=self.DB_CHOICES[0]
            )

        except IndexError:
            self.fields['corpus'] = forms.ChoiceField()

    # query = forms.CharField(max_length=255, initial='台北',help_text="""若要使用CQL，請您直接輸入CQL格式的索引，例 [pos = "V.*"][pos = "N.*"]""")

    # number_of_words = [(100, 100), (200, 200), (300, 300)]

    # 要顯示幾個詞field
    how_many_words = forms.IntegerField(
        label='詞數',
        widget=forms.NumberInput(attrs={'type': 'range', 'min': 100, 'max': 500}),
        initial=100,
    ) 

class WordSketchForm(forms.Form):
    """
    Form to answer which corpus to generate wordlist.
    """

    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.user = kwargs.pop('user', AnonymousUser())
        logging.debug('Authenticated!')

        # Generate DB_CHOICES based on AnonymousUser / Logined User
        if isinstance(self.user, AnonymousUser):
            self.DB_CHOICES = [(c.file_name.split('.')[0], f'{c.zh_name}')  # value, label
                           for c in Corpus.objects.filter(Q(is_public=True))]
        else:
            self.copens_user = CopensUser.objects.get(user=self.user)
            self.DB_CHOICES = [(c.file_name.split('.')[0], f'{c.zh_name} / {c.owner}')  # value, label
                           for c in Corpus.objects.filter(Q(owner=self.copens_user) | Q(is_public=True))]
        
        super().__init__(*args, **kwargs)  # must call super() to have access to fields

        # 要搜索的語料庫field
        try:
            self.fields['corpus'] = forms.ChoiceField(
                label="選擇語料庫",
                choices=self.DB_CHOICES,
                # widget=forms.CheckboxSelectMultiple,
                widget=forms.RadioSelect,
                initial=self.DB_CHOICES[0]
            )

        except IndexError:
            self.fields['corpus'] = forms.ChoiceField()

    # query = forms.CharField(max_length=255, initial='台北',help_text="""若要使用CQL，請您直接輸入CQL格式的索引，例 [pos = "V.*"][pos = "N.*"]""")

    # number_of_words = [(100, 100), (200, 200), (300, 300)]

    # 要搜索的關鍵字field
    query = forms.CharField(
        max_length=255,
        initial='台北',
        help_text="""
            請輸入欲搜尋的詞語
        """
    )

class CollocationForm(forms.Form):
    """
    Form to collect arguments for a collocation query.
    """

    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.user = kwargs.pop('user', AnonymousUser())
        logging.debug('Authenticated!')

        # Generate DB_CHOICES based on AnonymousUser / Logined User
        if isinstance(self.user, AnonymousUser):
            self.DB_CHOICES = [(c.file_name.split('.')[0], f'{c.zh_name}')  # value, label
                           for c in Corpus.objects.filter(Q(is_public=True))]
        else:
            self.copens_user = CopensUser.objects.get(user=self.user)
            self.DB_CHOICES = [(c.file_name.split('.')[0], f'{c.zh_name} / {c.owner}')  # value, label
                           for c in Corpus.objects.filter(Q(owner=self.copens_user) | Q(is_public=True))]
        
        super().__init__(*args, **kwargs)  # must call super() to have access to fields

        # 要搜索的語料庫field
        try:
            self.fields['corpus'] = forms.ChoiceField(
                label="選擇語料庫",
                choices=self.DB_CHOICES,
                # widget=forms.CheckboxSelectMultiple,
                widget=forms.RadioSelect,
                initial=self.DB_CHOICES[0]
            )

        except IndexError:
            self.fields['corpus'] = forms.ChoiceField()

    # query = forms.CharField(max_length=255, initial='台北',help_text="""若要使用CQL，請您直接輸入CQL格式的索引，例 [pos = "V.*"][pos = "N.*"]""")

    # number_of_words = [(100, 100), (200, 200), (300, 300)]

    # 要搜索的關鍵字field
    query = forms.CharField(
        max_length=255,
        initial='台北',
        help_text="""
            請輸入欲搜尋的詞語
        """
    )

    #
    left_context = forms.IntegerField(
        label='Left context',
        widget=forms.NumberInput(attrs={'type': 'range', 'min': 0, 'max': 10}),
        initial=5,
    ) 

    right_context = forms.IntegerField(
        label='Right context',
        widget=forms.NumberInput(attrs={'type': 'range', 'min': 0, 'max': 10}),
        initial=5,
    ) 

COPENS/templates/copens_static_pages/api_doc.html
{% extends 'copens_static_pages/generic/base.html' %}
{% block content %}
    
{% endblock content %}

COPENS/templates/copens_static_pages/query_collocation.html
{% extends 'copens_static_pages/generic/base.html' %}
{% block page_header %}
語料庫查詢: Collocation
{% endblock page_header %}
{% block content %}
{% load crispy_forms_tags %}

<section>
    <!-- <section style="padding: 30px 0"> -->
    <div class="container">
        {% if messages %}
        <div class="alert alert-info" role="alert">
            {% for m in messages %}
            <p>{{ m }}</p>
            {% endfor %}
        </div>
        {% endif %}
        
        {% include 'copens_static_pages/generic/query_nav.html' with current='collocation' %}
        
        <!-- Wordlist -->
        <div class="row">
            <div class="col s12">
                <div class="card z-depth-0">
                    <div class="card-content">
                        {{ form.errors }}
                        <form action="{% url 'static_pages:collocation_result' %}" method="get">
                            {{ form|crispy }}      
                            <button class="btn btn-primary" type="submit">搜尋</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>


</section>
{% endblock %}
{% block extra_js %}
<script>
// $('#window_size_value').text($('#id_context').val());
// $(document).on('input change', '#id_context', function() {
//     $('#window_size_value').html($(this).val());
// });
// $('#id_context').change(function (){
//     $('#window_size_value').text($('#id_context').val());
// })
</script>
{% endblock extra_js %}

COPENS/templates/copens_static_pages/query_concordance.html
{% extends 'copens_static_pages/generic/base.html' %}
{% block page_header %}
語料庫查詢
{% endblock page_header %}
{% block content %}
{% load crispy_forms_tags %}
<section>
    <!-- <section style="padding: 30px 0"> -->
    <div class="container">
        {% if messages %}
        <div class="alert alert-info" role="alert">
            {% for m in messages %}
            <p>{{ m }}</p>
            {% endfor %}
        </div>
        {% endif %}
        
        {% include 'copens_static_pages/generic/query_nav.html' with current="concordance" %}
        
        <!-- Concordance -->
        <div class="row">
            <div class="col s12 m8 l8">
                <div class="card z-depth-0">
                    <div class="card-content">
                        {{ form.errors }}
                        <form action="{% url 'static_pages:concordance_result' %}" method="get">
                            {{ form|crispy }}
                            <button class="btn btn-primary" type="submit">搜尋</button>
                        </form>
                    </div>
                </div>
            </div>

            <div class="col s12 m4 l4">

                <ul class="collection with-header">
                <li class="collection-header">關於搜尋字串</li>
                <!--
                <li class="collection-item">COPENS語料庫儲存與搜尋引擎係根據<a href="http://cwb.sourceforge.net/">CWB (The IMS Open Corpus
                                Workbench)</a>建置而成</li>
                            -->
                <li class="collection-item">有關CQL (Corpus Query Language)之使用可參閱<a href="http://cwb.sourceforge.net/files/CQP_Tutorial.pdf">CQP
                                Query Language Tutorial</a></li>
                </ul>

                <ul class="collection with-header">
                    <li class="collection-header">關於詞性標記(POS)</li>
                    <li class="collection-item">本網站使用<a href="http://ckipsvr.iis.sinica.edu.tw/papers/category_list.pdf">中研院平衡語料庫詞類標記系統</a></li>
                </ul>
                    
                    
            </div>
        </div>


</section>
{% endblock %}
{% block extra_js %}
<script>
// $('#window_size_value').text($('#id_context').val());
// $(document).on('input change', '#id_context', function() {
//     $('#window_size_value').html($(this).val());
// });
// $('#id_context').change(function (){
//     $('#window_size_value').text($('#id_context').val());
// })
</script>
{% endblock extra_js %}

COPENS/templates/copens_static_pages/query_word_sketch.html
{% extends 'copens_static_pages/generic/base.html' %}
{% block page_header %}
語料庫查詢: 詞彙特性素描
{% endblock page_header %}
{% block content %}
{% load crispy_forms_tags %}

<section>
    <!-- <section style="padding: 30px 0"> -->
    <div class="container">
        {% if messages %}
        <div class="alert alert-info" role="alert">
            {% for m in messages %}
            <p>{{ m }}</p>
            {% endfor %}
        </div>
        {% endif %}
        
        {% include 'copens_static_pages/generic/query_nav.html' with current='word_sketch' %}
        
        <!-- Wordlist -->
        <div class="row">
            <div class="col s12">
                <div class="card z-depth-0">
                    <div class="card-content">
                        {{ form.errors }}
                        <form action="{% url 'static_pages:word_sketch_result' %}" method="get">
                            {{ form|crispy }}      
                            <button class="btn btn-primary" type="submit">搜尋</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>


</section>
{% endblock %}
{% block extra_js %}
<script>
// $('#window_size_value').text($('#id_context').val());
// $(document).on('input change', '#id_context', function() {
//     $('#window_size_value').html($(this).val());
// });
// $('#id_context').change(function (){
//     $('#window_size_value').text($('#id_context').val());
// })
</script>
{% endblock extra_js %}

COPENS/templates/copens_static_pages/query_wordlist.html
{% extends 'copens_static_pages/generic/base.html' %}
{% block page_header %}
語料庫查詢: 詞彙列表
{% endblock page_header %}
{% block content %}
{% load crispy_forms_tags %}

<section>
    <!-- <section style="padding: 30px 0"> -->
    <div class="container">
        {% if messages %}
        <div class="alert alert-info" role="alert">
            {% for m in messages %}
            <p>{{ m }}</p>
            {% endfor %}
        </div>
        {% endif %}
        
        {% include 'copens_static_pages/generic/query_nav.html' with current='wordlist' %}
        
        <!-- Wordlist -->
        <div class="row">
            <div class="col s12">
                <div class="card z-depth-0">
                    <div class="card-content">
                        {{ form.errors }}
                        <form action="{% url 'static_pages:wordlist_result' %}" method="get">
                            {{ form|crispy }}      
                            <button class="btn btn-primary" type="submit">搜尋</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>


</section>
{% endblock %}
{% block extra_js %}
<script>
// $('#window_size_value').text($('#id_context').val());
// $(document).on('input change', '#id_context', function() {
//     $('#window_size_value').html($(this).val());
// });
// $('#id_context').change(function (){
//     $('#window_size_value').text($('#id_context').val());
// })
</script>
{% endblock extra_js %}

COPENS/templates/copens_static_pages/result_collocation.html
{% extends 'copens_static_pages/generic/base.html' %}
{% load my_tags %}
{% block page_header %}
    查詢結果: Collocation
{% endblock page_header %}


{% block content %}
<div class="row" id="page_header" style="background: #708aa1">
    <div class="container" style="margin-top: -20px">
        <div class="col s12 section" style="padding: 15px 0">
            <div class="col">
                <p>查詢詞彙: 
                    <span class="result-badge">{{ request.GET.query }}</span>
                </p>
            </div>
            <div class="col">
                <p>語料庫: 
                    {% for c in request.GET|get_list:'corpus' %}
                        <span class="result-badge">{{ c }}</span>
                    {% endfor %}
                </p>
            </div>
        </div>
    </div>
</div>
<section class="content-section" id="sketch_result_section">
    <div class="container">
        <div class="row">
            <div class="col s12">
                <a href="{% url 'copens_static_pages:wordlist' %}" class="waves-effect waves-light btn"><i class="material-icons left">refresh</i>重新查詢</a>
                <a href="{% url 'copens_static_pages:output_csv' %}" class="waves-effect waves-light btn disabled"><i class="material-icons left">file_copy</i>匯出 CSV 檔</a>
            </div>
        </div>

        <div class="row nomarginbottom">
            <div class="col s12">
                <div class="card">       
                    <div class="card-content">
                        <span class="card-title">{{ request.GET.query }}</span>
                        <p>語料中總詞頻 = {{ query_word_freq }}</p>
                    </div>
                </div>
            </div>
        </div>
    
        <div class="row">
            <div class="col s12">
                <div class="card">
                
                    <div class="card-content" id="concordance-card">
                        <table class="table table-hover highlight centered" style="width: 100%">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>詞彙</th>
                                    <th>語料庫中的總詞頻</th>
                                    <th>在所選區間中的總詞頻</th>
                                    <th>logDice分數</th>   
                                </tr>
                            </thead>
                            <tbody>
                                {% for result in results %}
                                <tr>
                                    <td>
                                        {{forloop.counter }}
                                    </td>
                                    <td>
                                        {{result.0}}
                                    </td>
                                    <td>
                                        {{result.1.freq_in_wordlist}}
                                    </td>
                                    <td>
                                        {{result.1.freq_in_collocates}}
                                    </td>
                                    <td>
                                        {{result.1.log_dice}}
                                    </td>
                                </tr>                                  
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>

                </div>
            </div>
        </div>

        
    </div>
</section>
{% endblock %}

COPENS/templates/copens_static_pages/result_concordance.html
{% extends 'copens_static_pages/generic/base.html' %}
{% load my_tags %}
{% block page_header %}
    查詢結果
{% endblock page_header %}


{% block content %}
<div class="row" id="page_header" style="background: #708aa1">
    <div class="container" style="margin-top: -20px">
        <div class="col s12 section" style="padding: 15px 0">
            <div class="col">
                <p>搜尋字串: 
                    <span class="result-badge">{{ request.GET.query }}</span>
                </p>
            </div>
            <div class="col">
                <p>上下文視窗大小: 
                    <span class="result-badge">{{ request.GET.context }}</span>
                </p>
            </div>
            <div class="col">
                <p>語料庫: 
                    {% for c in request.GET|get_list:'corpora' %}
                        <span class="result-badge">{{ c }}</span>
                    {% endfor %}
                </p>
            </div>
            <div class="col">
                <p>顯示詞性: 
                    <span class="result-badge">
                        {% if request.GET.show_pos %}
                            是
                        {% else %}
                            否
                        {% endif %}
                    </span>
                </p>
            </div>
            <div class="col">
                <p>總筆數:
                    <span class="result-badge">{{ results.total }} 筆</span>
                </p>
            </div>

        </div>
    </div>
</div>
<section class="content-section">
    <div class="container">
        <div class="row">
            <div class="col s12">
                <a href="{% url 'copens_static_pages:concordance' %}" class="waves-effect waves-light btn"><i class="material-icons left">refresh</i>重新查詢</a>
                <a href="{% url 'copens_static_pages:output_csv' %}" class="waves-effect waves-light btn"><i class="material-icons left">file_copy</i>匯出 CSV 檔</a>
            </div>
        </div>
        <!--
        <div class="row">
            <div class="col s12">
                <div class="card" style="margin-bottom: 2em">
                    <div class="card-content">
                        <h5 class="card-title">查詢條件</h5>
                        <div class="row">
                            <div class="col">
                                <p>搜尋字串: <span class="badge badge-dark badge-pill">{{ request.GET.query }}</span></p>
                            </div>
                            <div class="col">
                                <p>上下文視窗大小: <span class="badge badge-dark badge-pill">{{ request.GET.context }}</span></p>
                            </div>
                            <div class="col">
                                <p>語料庫: {% for c in request.GET|get_list:'corpora' %}
                                    <span class="badge badge-dark badge-pill">{{ c }}</span>
                                {% endfor %}
                                    </p>
                            </div>
                            <div class="col">
                                <p>顯示詞性: <span class="badge badge-dark badge-pill">
                        {% if request.GET.show_pos %}
                        是
                        {% else %}
                        否
                    {% endif %}
                    </span> </p>
                            </div>
                            <div class="col">
                                <p>總筆數: <span class="badge badge-dark badge-pill">{{ results.total }} 筆</span></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    -->
        <div class="row">
            <div class="col s12">
                <div class="pagination center-align">
                    <p class="current">
                        第 {{ results.number }} 頁（共 {{ results.paginator.num_pages }} 頁）
                    </p>
                </div>
                <div class="pagination center-align">
                    <p class="step-links">
                        {% if results.has_previous %}
                        <a href="?{% param_replace page=1 %}">&laquo; 最首頁</a>
                        <a href="?{% param_replace page=results.previous_page_number %}">上一頁</a>
                        {% endif %}
                        {% if results.has_next %}
                        <a href="?{% param_replace page=results.next_page_number %}">下一頁</a>
                        <a href="?{% param_replace page=results.paginator.num_pages %}">最末頁 &raquo;</a>
                        {% endif %}
                    </p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col s12">
                <div class="card">
                    
                        <div class="card-content" id="concordance-card">
                            <table class="table table-hover" style="width: 100%">
                                <tbody>
                                    {% for result in results.object_list %}
                                    <tr>
                                        <td>
                                            <div class="row">
                                                <div class="col s5 right-align">
                                                    {{ result.context_left }}
                                                </div>
                                                <div class="col s2 center-align">
                                                    {{ result.query_word }}
                                                </div>
                                                <div class="col s5 left-align">
                                                    {{ result.context_right }}
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>

                </div>
            </div>
        </div>
        <div class="row">
            <div class="col s12">
                <div class="pagination center-align">
                    <p class="current">
                        第 {{ results.number }} 頁（共 {{ results.paginator.num_pages }} 頁）
                    </p>
                </div>
                <div class="pagination center-align">
                    <p class="step-links">
                        {% if results.has_previous %}
                        <a href="?{% param_replace page=1 %}">&laquo; 最首頁</a>
                        <a href="?{% param_replace page=results.previous_page_number %}">上一頁</a>
                        {% endif %}
                        {% if results.has_next %}
                        <a href="?{% param_replace page=results.next_page_number %}">下一頁</a>
                        <a href="?{% param_replace page=results.paginator.num_pages %}">最末頁 &raquo;</a>
                        {% endif %}
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

COPENS/templates/copens_static_pages/result_word_sketch.html
{% extends 'copens_static_pages/generic/base.html' %}
{% load my_tags %}
{% block page_header %}
    查詢結果: 詞彙特性素描
{% endblock page_header %}


{% block content %}
<div class="row" id="page_header" style="background: #708aa1">
    <div class="container" style="margin-top: -20px">
        <div class="col s12 section" style="padding: 15px 0">
            <div class="col">
                <p>查詢詞彙: 
                    <span class="result-badge">{{ request.GET.query }}</span>
                </p>
            </div>
            <div class="col">
                <p>語料庫: 
                    {% for c in request.GET|get_list:'corpus' %}
                        <span class="result-badge">{{ c }}</span>
                    {% endfor %}
                </p>
            </div>
        </div>
    </div>
</div>
<section class="content-section" id="sketch_result_section">
    <div class="container">
        <div class="row">
            <div class="col s12">
                <a href="{% url 'copens_static_pages:wordlist' %}" class="waves-effect waves-light btn"><i class="material-icons left">refresh</i>重新查詢</a>
                <a href="{% url 'copens_static_pages:output_csv' %}" class="waves-effect waves-light btn disabled"><i class="material-icons left">file_copy</i>匯出 CSV 檔</a>
            </div>
        </div>
    
        <div class="row nomarginbottom">
            <div class="col s12">
                <div class="card">       
                    <div class="card-content">
                        <span class="card-title">{{ request.GET.query }}</span>
                        <p>語料中總詞頻 = {{ query_word_freq }}</p>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            {% for sketch_name, table in results.items %}
                <div class="col l4 m4 s12">
                    <div class="card">       
                        <div class="card-content" style="background-color: #b7c4d0">
                            <span class="card-title nomarginbottom ">{{ sketch_name }} 
                                <span class="smaller">freq = {{ table.freq }}</span>
                            </span>
                            
                        </div>
                        <div class="card-action">
                            <table>
                                {% for word, t in table.result %}
                                    <tr>
                                        <td>{{word}}</td>
                                        <td>{{t.freq}}</td>
                                        <td>{{t.log_dice}}</td>
                                    </tr>
                                {% endfor %}

                            </table>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>


        
    </div>
</section>
{% endblock %}