COPENS/COPENS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from copens_static_pages import views
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('user/', include('createcorpora.urls', namespace='create')),
    path('', include('copens_static_pages.urls', namespace='static_pages')),
    path('django-rq/', include('django_rq.urls'))
]

urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls))
    ]

COPENS/copens_static_pages/urls.py
from django.urls import path
from . import views

app_name = 'copens_static_pages'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('about', views.About.as_view(), name='about'),
    path('term_of_use', views.TermOfUse.as_view(), name='term_of_use'),
    path('contact', views.Contact.as_view(), name='contact'),
    path('api_doc', views.ApiDoc.as_view(), name='api_doc'),
    path('query', views.Query.as_view(), name='query'),
    path('result', views.ConcordanceResultView.as_view(), name='concordance_result'),
    path('concordance', views.ConcordanceQueryView.as_view(), name='concordance'),
    path('wordlist_result', views.WordlistResultView.as_view(), name='wordlist_result'),
    path('wordlist', views.WordListQueryView.as_view(), name='wordlist'),
    path('word_sketch', views.WordSketchQueryView.as_view(), name='word_sketch'),
    path('word_sketch_result', views.WordSketchResultView.as_view(), name='word_sketch_result'),
    path('collocation', views.CollocationQueryView.as_view(), name='collocation'),
    path('collocation_result', views.CollocationResultView.as_view(), name='collocation_result'),
    path('output_csv', views.output_csv, name='output_csv'),






    # path('create/', UploadCorporaView.as_view(), name='upload')
]

COPENS/createcorpora/urls.py
from django.urls import path
from .views import UploadCorporaView, UploadedView, DeleteCorpusView


app_name = 'upload'

urlpatterns = [
    path('', UploadCorporaView.as_view(), name='home'),
    path('upload/', UploadCorporaView.as_view(), name='upload'),
    path('uploaded/', UploadedView.as_view(), name='uploaded'),
    # path('concordance/', SearchView.as_view(), name='concordance'),
    # path('results/', ResultsView.as_view(), name='results'),
    path('delete/<int:pk>', DeleteCorpusView.as_view(), name='delete')
]

COPENS/createcorpora/models.py
from django.db import models
from django.contrib.auth.models import User


class CopensUser(models.Model):
    class Meta:
        verbose_name_plural = 'COPENS users'
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='copens_user')
    raw_dir = models.CharField(max_length=255)
    data_dir = models.CharField(max_length=255)
    registry_dir = models.CharField(max_length=255)

    def __str__(self):
        return self.user.username


class Corpus(models.Model):
    class Meta:
        verbose_name_plural = 'Corpora'
    owner = models.ForeignKey(CopensUser, on_delete=models.SET_NULL, null=True, blank=True, related_name='corpora')
    en_name = models.CharField(max_length=255)
    zh_name = models.CharField(max_length=255)
    file_name = models.CharField(max_length=255, default="")
    is_public = models.BooleanField(default=False)
    date_uploaded = models.DateTimeField(auto_now_add=True)
    tcsl_doc_id = models.CharField(max_length=255, default="")
    tcsl_corpus_name = models.CharField(max_length=255, default="")

    def __str__(self):
        return f'{self.en_name} / {self.zh_name} / {self.owner.user.username}'

COPENS/createcorpora/forms.py
"""
Forms to deal with creating corpora or searching within corpora.
"""

import logging

from django import forms
from django.db.models import Q
from django.contrib.auth.models import AnonymousUser

from .models import Corpus, CopensUser

logger = logging.getLogger(__name__)


class UploadCorpusForm(forms.Form):
    """Upload a corpus."""
    zh_name = forms.CharField(max_length=255, initial='中研院平衡語料庫', label='語料庫名稱(中文)')
    en_name = forms.CharField(max_length=255, initial='ASBC', label='語料庫名稱(英文)')
    file = forms.FileField(label='檔案', help_text='檔案名稱必須與語料庫名稱(英文)相同')
    needs_preprocessing = forms.BooleanField(required=False, help_text='我們可以幫您做前處理的部份',
                                             label='自動處理')
    is_public = forms.BooleanField(required=False, help_text="您是否希望公開這份語料庫嗎？",
                                   label='設為公開')
    positional_attrs = forms.CharField(max_length=255, help_text="Please prepend each attribute with a '-P'.",
                                       required=False, initial='-P pos',
                                       label='位置屬性(Positional attributes)')
    structural_attrs = forms.CharField(max_length=255, help_text="Please prepend each attribute with a '-S'.",
                                       required=False, initial='-S text+id -S s -0 corpus',
                                       label='結構屬性(Structural attributes)')

    def clean_positional_attrs(self):
        cleaned_data = self.cleaned_data['positional_attrs']
        if cleaned_data and not cleaned_data.startswith('-P'):
            raise forms.ValidationError("Positional attributes must begin with -P", code='invalid')
        return cleaned_data

    def clean_structural_attrs(self):
        cleaned_data = self.cleaned_data['structural_attrs']
        if cleaned_data and not cleaned_data.startswith('-S'):
            raise forms.ValidationError("Structural attributes must begin with -S", code='invalid')
        return cleaned_data

    def clean_file(self):
        cleaned_data = self.cleaned_data['file']
        if not cleaned_data.name.isascii():
            raise forms.ValidationError("You may only use the characters A to Z, 0 to 9, "
                                        "and simple punctuation in your password.")
        return cleaned_data


class SearchForm(forms.Form):
    """
    Form to search databases. Choices are populated with public corpora and a user's corpora, if logged in.
    """

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', AnonymousUser())
        logging.debug('Authenticated!')
        self.copens_user = CopensUser.objects.get(user=self.user)
        self.DB_CHOICES = [(c.file_name.split('.')[0], f'{c.zh_name} / {c.owner}')  # value, label
                           for c in Corpus.objects.filter(Q(owner=self.copens_user) | Q(is_public=True))]
        super().__init__(*args, **kwargs)  # must call super() to have access to fields
        print('self.DB_CHOICES')
        print(self.DB_CHOICES)
        try:
            self.fields['corpora'] = forms.MultipleChoiceField(
                label="選擇語料庫",
                choices=self.DB_CHOICES,
                widget=forms.CheckboxSelectMultiple,
                initial=self.DB_CHOICES[0]
            )
        except IndexError:
            self.fields['corpora'] = forms.MultipleChoiceField()

    query = forms.CharField(max_length=255, initial='台北',
                            help_text="""若要使用CQL，請您直接輸入CQL格式的索引，例 [pos = "V.*"][pos = "N.*"]""")

    CHOICES = [(n, n) for n in range(1, 31)]
 
    context = forms.ChoiceField(label="Window size", choices=CHOICES)
    show_pos = forms.BooleanField(label="顯示詞性(POS)", required=False)

COPENS/createcorpora/views.py
import logging
from pathlib import Path

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import DeleteView
from django.views.generic import View, TemplateView
from django.views.generic.edit import FormView
from django.views.generic.list import ListView
from redis import Redis
from rq import Queue

from . import utils
from .forms import UploadCorpusForm, SearchForm
from .mixins import MultiFormsView
from .models import Corpus, CopensUser

logger = logging.getLogger(__name__)

redis_conn = Redis(host='redis')
q = Queue(connection=redis_conn)

class Home(ListView):
    template_name = 'createcorpora/home.html'
    model = Corpus
    paginate_by = 100

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            user = CopensUser.objects.get(user=self.request.user)
            context['private_corpora'] = Corpus.objects.filter(owner=user)
        context['public_corpora'] = Corpus.objects.filter(is_public=True)
        return context


class SearchView(FormView):
    """
    User chooses what databases to query from.
    """

    template_name = 'createcorpora/query_concordance.html'
    form_class = SearchForm

    def get_form_kwargs(self):
        """
        Add the current logged in user to the form's context.
        """
        kwargs = super().get_form_kwargs()

        kwargs['user'] = self.request.user
        return kwargs

    def form_invalid(self, form):
        print(form.errors)


class ResultsView(View):
    """
    Results after querying CWB are returned here.
    """
    template_name = 'createcorpora/results.html'

    def get(self, request):
        if not self.request.GET.getlist('corpora'):
            messages.warning(self.request, '請至少選擇一個語料庫')
            if self.request.user.is_authenticated:
                return redirect('create:home')
            else:
                return redirect('static_pages:query')

        if self.request.GET.get('page'):
            results_list = self.request.session.get('results_list')
            paginator = Paginator(results_list, 20)
            page = request.GET.get('page')
            results = paginator.get_page(page)
            results.total = len(results_list)
            results.object_list = list(map(for_concordance_tag, results.object_list))
            return render(request, self.template_name, {'results': results})

        form = SearchForm(self.request.GET, user=self.request.user)

        if form.is_valid():
            results_list = []
            if self.request.user.is_authenticated:
                user_registry = utils.get_user_registry(self.request)
            else:
                user_registry = None
            results_dict = utils.cqp_query(user_registry=user_registry, **form.cleaned_data)
            print(results_dict)
            for corpus, path in results_dict.items():
                try:
                    results_list.extend(utils.read_results(path))
                except FileNotFoundError:
                    messages.error(request, '查詢語法有誤！')
                    redirect('create:home')

            paginator = Paginator(results_list, 50)
            page = request.GET.get('page')
            results = paginator.get_page(page)
            results.total = len(results_list)
            results.object_list = list(map(for_concordance_tag, results.object_list))
            self.request.session['results_list'] = results_list
            print(results.object_list)
            return render(request, self.template_name, {'results': results})
        else:
            print(form.errors)
            if self.request.user.is_authenticated:
                return redirect('create:concordance')
            else:
                return redirect('static_pages:query')



def for_concordance_tag(elm):
    import re
    p = re.compile('<(.*)>')
    query_word = p.search(elm).group(1)
    context_left = elm.split('<')[0].replace('<LI>', '')
    context_right = elm.split('>')[1].replace('</LI>', '')

    return {
        'context_left': context_left,
        'query_word': query_word,
        'context_right': context_right
    }


class UploadCorporaView(LoginRequiredMixin, FormView):
    """
    User can upload personal corpora to COPENS.
    """
    login_url = 'account_login'
    template_name = 'createcorpora/upload.html'
    form_class = UploadCorpusForm
    success_url = reverse_lazy('create:home')

    def form_valid(self, form):
        logger.debug(list(form.cleaned_data.items()))
        file = form.cleaned_data['file']
        p_attrs = form.cleaned_data['positional_attrs']
        s_attrs = form.cleaned_data['structural_attrs']
        zh_name = form.cleaned_data['zh_name']
        en_name = form.cleaned_data['en_name']
        is_public = form.cleaned_data['is_public']
        needs_preprocessing = form.cleaned_data['needs_preprocessing']

        # if filename != en_name.lower():
        #     messages.warning(self.request, '上傳失敗：您檔名與語料庫英文名字不同！')
        #     return redirect('create:home')

        copens_user = get_object_or_404(CopensUser, user=self.request.user)
        raw_dir = Path(copens_user.raw_dir)
        data_dir = Path(copens_user.data_dir)
        registry_dir = Path(copens_user.registry_dir)

        filename = utils.does_file_already_exist(file, raw_dir)
        print(filename)
        # filename = utils.save_file_to_drive(file, raw_dir)
        if not filename:
            messages.warning(self.request, '上傳失敗：您上傳的語料庫已存在！')
            return redirect('create:home')

        filename = utils.save_file_to_drive(file, raw_dir)
        print(filename)

        # Upload a copy to TCSL
        # if success: save `tcsl.tcsl_doc_id` and `tcsl.tcsl_corpus_name` into Corpus model

        # tcsl = utils.TCSL()
        # tcsl_upload_success = tcsl.upload(file, raw_dir / file.name)
        # print("TCSL", tcsl_upload_success)
        # print('TCSL', tcsl.tcsl_doc_id)
        # print('TCSL', tcsl.tcsl_corpus_name)

        if needs_preprocessing:
            logger.debug(f'Preprocessing: {filename}')
            s_attrs = ""
            p_attrs = "-P pos"

            # Step 1: 先將文本清理乾淨，斷詞，產生.vrt檔，並存進raw_dir
            preprocess_job = q.enqueue(utils.preprocess, raw_dir / filename, raw_dir=raw_dir)
            filename = f'{filename}.vrt'

        # Step 2: 對.vrt檔進行cwb-encode指令
        encode_job = q.enqueue(utils.cwb_encode, vrt_file=raw_dir / filename, data_dir=data_dir,
                               registry_dir=registry_dir, p_attrs=p_attrs, s_attrs=s_attrs,)

        # Step 3: 進行cwb-make指令
        make_job = q.enqueue(utils.cwb_make, Path(filename).stem, registry_dir, depends_on=encode_job)

        # Step 4: 如果前面都成功，將這個新語料庫的metadata存進DB
        create_corpus_job = q.enqueue(
            utils.create_corpus,
            copens_user=copens_user,
            zh_name=zh_name,
            en_name=en_name,
            is_public=is_public,
            file_name=filename,
            registry_dir=registry_dir,
            # tcsl_doc_id=tcsl.tcsl_doc_id,
            # tcsl_corpus_name=tcsl.tcsl_corpus_name,
            # tcsl_upload_success=tcsl_upload_success,
            depends_on=make_job)
        # Corpus.objects.create(
        #     owner=copens_user,
        #     zh_name=zh_name,
        #     en_name=en_name,
        #     is_public=is_public,
        #     file_name=file.name,
        # )
        # if is_public:
        #     q.enqueue(utils.make_public, registry_dir, file.name, depends_on=make_job)

        # os.link(registry_dir.joinpath(file.name.split('.')[0]),
        #         Path(settings.CWB_PUBLIC_REG_DIR).joinpath(file.name.split('.')[0].lower()),
        #         )

        # utils.cwb_encode(vrt_file=raw_dir / file.name, data_dir=data_dir,
        #                  registry_dir=registry_dir, p_attrs=p_attrs, s_attrs=s_attrs)
        # utils.cwb_make(Path(file.name).stem, registry_dir=registry_dir)

        # if the file is plain text (which means it's "needs_preprocessing" is True)
        # should upload to TSCL as well, in order to get more functions

        # if tcsl_upload_success:
        #     Corpus.objects.create(
        #         owner=copens_user,
        #         zh_name=zh_name,
        #         en_name=en_name,
        #         is_public=is_public,
        #         file_name=file.name,
        #         tcsl_doc_id=tcsl.tcsl_doc_id,
        #         tcsl_corpus_name=tcsl.tcsl_corpus_name
        #     )
        #
        # else:
        #     Corpus.objects.create(
        #         owner=copens_user,
        #         zh_name=zh_name,
        #         en_name=en_name,
        #         is_public=is_public,
        #         file_name=file.name,
        #     )
        #
        # if is_public:
        #     os.link(registry_dir.joinpath(file.name.split('.')[0]),
        #             Path(settings.CWB_PUBLIC_REG_DIR).joinpath(file.name.split('.')[0].lower()),
        #             )
        messages.warning(self.request, '語料上傳成功！')
        return super().form_valid(form)


class UploadedView(TemplateView):
    """
    顯示使用者已上傳的語料庫
    """

    template_name = 'createcorpora/uploaded.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        copens_user = CopensUser.objects.get(user=self.request.user)
        private_corpora = Corpus.objects.filter(owner=copens_user)
        public_corpora = Corpus.objects.filter(is_public=True)
        context['no_corpus'] = True if len(private_corpora) == 0 and len(public_corpora) == 0 else False
        context['private_corpora'] = private_corpora
        return context


class DeleteCorpusView(LoginRequiredMixin, DeleteView):

COPENS/templates/createcorpora/corpus_confirm_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
        <div class="container">
            <div class="row">
                <div class="col">
                    <form method="post">{% csrf_token %}
                        <p>Are you sure you want to delete "{{ object }}"?</p>
                        <input type="submit" value="Confirm">
                    </form>
                </div>
            </div>
        </div>
{% endblock content %}

COPENS/templates/createcorpora/index.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="row">
    <div class="col">
        <h1>Upload a corpus</h1>
        <form action="{% url 'create:upload' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-primary" type="submit">Upload</button>
        </form>
    </div>
    </div>
{% endblock content %}

COPENS/templates/createcorpora/search.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <form action="{% url 'create:results' %}" method="get">
    {{ form|crispy }}
    <button class="btn btn-primary" type="submit">Search</button>
    </form>
{% endblock content %}

COPENS/templates/createcorpora/upload.html
{% extends 'createcorpora/user_base.html' %}

{% block page_header %}
	使用者後台 > 上傳語料
{% endblock page_header %}

{% block user_panel_content %}

{% load crispy_forms_tags %}
<form action="{% url 'create:upload' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-outline-primary btn-block" type="submit">上傳</button>
</form>

{% endblock user_panel_content %}

COPENS/templates/createcorpora/uploaded.html
{% extends 'createcorpora/user_base.html' %}

{% block page_header %}
    使用者後台 > 已上傳語料
{% endblock page_header %}

{% block user_panel_content %}

{% load crispy_forms_tags %}

<table class="table table-hover table-sm">
    <thead class="thead-light">
    <tr>
        <th scope="col">#</th>
        <th scope="col">上傳日期時間</th>
        <th scope="col">英文名稱</th>
        <th scope="col">中文名稱</th>
        <th scope="col">是否公開</th>
        <th scope="col">刪除</th>

    </tr>
    </thead>
    <tbody>

    {% for corpus in private_corpora %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ corpus.date_uploaded|date:'M d, Y H:i' }}</td>
            <td>{{ corpus.en_name }}</td>
            <td>{{ corpus.zh_name }}</td>
            <td>{{ corpus.is_public }}</td>
            <td><a class="delete_button red-text text-darken-4" href="{% url 'create:delete' pk=corpus.id %}" id="{{ corpus.id }}"><i
                    class="fa fa-trash-alt"></i></a></td>
        </tr>
    {% endfor %}
    </tbody>
</table>

{% endblock user_panel_content %}

COPENS/templates/createcorpora/user_base.html
{% extends 'copens_static_pages/generic/base.html' %}

{% block page_header %}
	使用者後台
{% endblock page_header %}



{% block content %}

<section class="section content-section" id="user-panel-section">

	<div class="container">
	    {% if messages %}
	        <div class="alert alert-info" role="alert">
	            {% for m in messages %}
	                <p>{{ m }}</p>
	            {% endfor %}
	        </div>
	    {% endif %}
	
	    <div class="row">
	        <div class="col l3" id="user_panel_menu">
	            <ul>
	                <li><a href="{% url 'create:upload' %}">上傳語料</a></li>
	                <li><a href="{% url 'create:uploaded' %}">已上傳語料</a></li>
	                <li><a href="#">帳號資訊</a></li>
	                <!--
	                <li>查詢語料庫</li>
	                <ul>
	                	<li><a href="{#{% url 'create:concordance' %}#}">Concordance</a></li>
	                	
	                </ul>
	            	-->
	            </ul>
	        </div>
	        <div class="col l9">
	                {% block user_panel_content %}
	                {% endblock %}
	        </div>                 
	    </div>
	</div>
</section>

{% endblock content %}

COPENS/templates/createcorpora/user_panel.html
{% extends 'copens_static_pages/generic/base.html' %}
{% block page_header %}
使用者後台
{% endblock %}

{% block content %}
    {% load crispy_forms_tags %}
    <!-- Confirm delete modal -->
    <div class="modal" tabindex="-1" role="dialog" id="confirm_delete_modal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">刪除語料庫</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>確定要刪除語料庫？按下確認後，刪除動作將無法復原。</p>
                </div>
                <div class="modal-footer">
                    <form id="delete_form" method="post" action="">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary">確認</button>
                    </form>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">取消</button>
                </div>
            </div>
        </div>
    </div>


    <section class="section content-section" id="user-panel-section">

        <div class="container">
            {% if messages %}
                <div class="alert alert-info" role="alert">
                    {% for m in messages %}
                        <p>{{ m }}</p>
                    {% endfor %}
                </div>

            {% endif %}
            <div class="row">
                <div class="col-3">
                    <ul>
                        <li>
                            上傳語料
                        </li>
                        <li>
                            已上傳語料
                        </li>
                        <li>
                            帳號資訊
                        </li>

                    </ul>
                </div>
                <div class="col-9">
                    <ul class="nav nav-tabs" id="myTab" role="tablist">
                        
                        <li class="nav-item">
                            <a class="nav-link active" id="upload-corpus-tab" data-toggle="tab" href="#upload-corpus" role="tab"
                               aria-controls="upload-corpus" aria-selected="true">上傳語料</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="uploaded-corpus-tab" data-toggle="tab" href="#uploaded-corpus" role="tab"
                               aria-controls="uploaded-corpus" aria-selected="true">已上傳語料</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="concordance-tab" data-toggle="tab" href="#concordance" role="tab"
                               aria-controls="concordance" aria-selected="false">Concordance</a>
                        </li>
                        <!--
                        <li class="nav-item">
                            <a class="nav-link" id="keyness-tab" data-toggle="tab" href="#keyness" role="tab"
                               aria-controls="keyness" aria-selected="false">Keyness</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="n-gram-tab" data-toggle="tab" href="#n-gram" role="tab"
                               aria-controls="n-gram" aria-selected="false">N-gram</a>
                        </li>
                    -->

                    </ul>
                    <div class="tab-content" id="myTabContent">
                        
                        <!-- 上傳語料 -->
                        <div class="tab-pane fade show active" id="upload-corpus" role="tabpanel" aria-labelledby="upload-corpus-tab">
                            <div class="row">
                                <div class="col-lg-12">
                                    <section>
                                        <form action="{% url 'create:upload' %}" method="post"
                                              enctype="multipart/form-data">
                                            {% csrf_token %}
                                            {{ forms.upload|crispy }}

                                            <button class="btn btn-outline-primary btn-block" type="submit">Upload
                                            </button>


                                        </form>
                                    </section>
                                    
                                </div>

                            </div>
                        </div>
                        
                        <!-- 已上傳語料 -->
                        <div class="tab-pane fade" id="uploaded-corpus" role="tabpanel" aria-labelledby="uploaded-corpus-tab">
                            <div class="row">
                                <div class="col-lg-12">
                                    <section>
                                        <h4>目前已上傳語料</h4>
                                        <table class="table table-hover table-sm">
                                            <thead class="thead-light">
                                            <tr>
                                                <th scope="col">#</th>
                                                <th scope="col">上傳日期時間</th>
                                                <th scope="col">英文名稱</th>
                                                <th scope="col">中文名稱</th>
                                                <th scope="col">是否公開</th>
                                                <th scope="col">刪除</th>

                                            </tr>
                                            </thead>
                                            <tbody>

                                            {% for corpus in private_corpora %}
                                                <tr>
                                                    <th scope="row">{{ forloop.counter }}</th>
                                                    <td>{{ corpus.date_uploaded|date:'M d, Y H:i' }}</td>
                                                    <td>{{ corpus.en_name }}</td>
                                                    <td>{{ corpus.zh_name }}</td>
                                                    <td>{{ corpus.is_public }}</td>
                                                    <td><a class="delete_button" href="#" id="{{ corpus.id }}"><i
                                                            class="fa fa-trash-alt"></i></a></td>
                                                    <!-- <td><a class="btn btn-primary btn-sm" href="{% url 'create:delete' pk=corpus.id %}">刪掉</a></td> -->
                                                </tr>
                                            {% endfor %}
                                            </tbody>
                                        </table>
                                    </section>
                                </div>

                            </div>
                        </div>
                        
                        <!-- Concordance query -->
                        <div class="tab-pane fade" id="concordance" role="tabpanel"
                             aria-labelledby="concordance-tab">

                            <section>

                                {% if no_corpus %}
                                    <div class="alert alert-info" role="alert">

                                        <p>尚無可用語料庫</p>

                                    </div>
                                {% else %}
                                    <form action="{% url 'create:results' %}" method="get">
                                        {{ forms.search|crispy }}
                                        <button class="btn btn-primary" type="submit">Search</button>
                                    </form>
                                {% endif %}
                            </section>
                        </div>

                        <!-- Keyness query -->
                        <!--
                        <div class="tab-pane fade" id="keyness" role="tabpanel"
                             aria-labelledby="keyness-tab">

                            <section>

                                {% if no_corpus %}
                                    <div class="alert alert-info" role="alert">

                                        <p>請先上傳語料庫</p>

                                    </div>
                                {% else %}
                                    <form action="{% url 'create:results' %}" method="get">
                                        {{ forms.keyness|crispy }}
                                        <button class="btn btn-primary" type="submit">Search</button>
                                    </form>
                                {% endif %}
                            </section>
                        </div>
                        ->>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

{% block extra_js %}
    <script>
        $('.delete_button').on('click', function (e) {
            var clicked_corpus_id = $(this).attr('id');
            var url = '{% url "create:delete" pk=0 %}';
            var url = url.replace('/0', '/' + clicked_corpus_id);
            $('#delete_form').attr('action', url);
            $('#confirm_delete_modal').modal('show');
        });

        // $('input.slider').slider();
    </script>
    <script>
    $("#id_needs_preprocessing").change(function() {
        if($(this).prop('checked')) {
            $('#id_positional_attrs').attr("disabled", true);
            $('#id_structural_attrs').attr("disabled", true);
        } else {
            $('#id_positional_attrs').attr("disabled", false);
            $('#id_structural_attrs').attr("disabled", false);
        }
    })


    </script>
{% endblock extra_js %}  